name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deployment 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the React app
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Or your desired branch for hosting
          folder: build # Specifies the directory containing the build files
